[package]
name = "rust-aoc-2022"
version = "0.1.0"
edition = "2021"
default-run = "day02"

[[bin]]
name = "day01"
path = "src/day01.rs"

[[bin]]
name = "day02"
path = "src/day02.rs"

[[bin]]
name = "day03"
path = "src/day03.rs"

[dependencies]
regex = "1"
itertools = "0.10"
